// js/supabaseApi.js — WOW Surprises · Role-Aware Auth + Full API
// ✅ Supports roles: customer | merchant | admin
// ✅ Correct column names: surprise_date, surprise_time, recipient_address
// ✅ Booking reference auto-generated by DB trigger

let supabaseClient = null;

function initializeSupabase() {
  if (!window.SUPABASE_CONFIG) {
    console.error('❌ Supabase config not found. Check config.js');
    return null;
  }
  if (!supabaseClient) {
    supabaseClient = window.supabase.createClient(
      window.SUPABASE_CONFIG.url,
      window.SUPABASE_CONFIG.anonKey
    );
    console.log('✅ Supabase client initialized');
  }
  return supabaseClient;
}

// ─────────────────────────────────────────────────────────────────────────────
// Storage helpers
// ─────────────────────────────────────────────────────────────────────────────
const Storage = {
  set(key, value)    { try { localStorage.setItem(key, JSON.stringify(value)); } catch(e) {} },
  get(key)           { try { return JSON.parse(localStorage.getItem(key)); } catch(e) { return null; } },
  remove(key)        { try { localStorage.removeItem(key); } catch(e) {} }
};
const SessionStorage = {
  set(key, value)    { try { sessionStorage.setItem(key, JSON.stringify(value)); } catch(e) {} },
  get(key)           { try { return JSON.parse(sessionStorage.getItem(key)); } catch(e) { return null; } },
  remove(key)        { try { sessionStorage.removeItem(key); } catch(e) {} }
};

// ─────────────────────────────────────────────────────────────────────────────
// API Namespace
// ─────────────────────────────────────────────────────────────────────────────
const API = {

  init() { return initializeSupabase(); },

  // ── AUTH ──────────────────────────────────────────────────────────────────
  auth: {

    /**
     * Sign up a new user with role stored in user_metadata.
     * @param {string} email
     * @param {string} password
     * @param {object} userData  — { name, phone, role, business_name? }
     */
    async signUp(email, password, userData = {}) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');

      const role = userData.role || 'customer'; // default to customer

      const { data, error } = await client.auth.signUp({
        email,
        password,
        options: {
          data: {
            full_name:     userData.name  || '',
            phone:         userData.phone || '',
            role:          role,
            business_name: userData.business_name || null,
          }
        }
      });
      if (error) throw error;

      if (data.user) {
        const userInfo = {
          id:            data.user.id,
          email:         data.user.email,
          name:          userData.name,
          phone:         userData.phone,
          role:          role,
          business_name: userData.business_name || null,
          created_at:    new Date().toISOString()
        };
        Storage.set('currentUser', userInfo);
      }
      return data;
    },

    /**
     * Sign in with optional role verification.
     * @param {string}  email
     * @param {string}  password
     * @param {boolean} rememberMe
     * @param {string|null} expectedRole  — if provided, throws if role doesn't match
     */
    async signIn(email, password, rememberMe = false, expectedRole = null) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');

      const { data, error } = await client.auth.signInWithPassword({ email, password });
      if (error) throw error;

      const user     = data.user;
      const userRole = user.user_metadata?.role || 'customer';

      // Role mismatch guard
      if (expectedRole && userRole !== expectedRole) {
        await client.auth.signOut();
        throw new Error(`This account is registered as "${userRole}". Please select the correct role.`);
      }

      const userInfo = {
        id:    user.id,
        email: user.email,
        name:  user.user_metadata?.full_name || user.email.split('@')[0],
        phone: user.user_metadata?.phone || '',
        role:  userRole,
        business_name: user.user_metadata?.business_name || null,
        created_at: user.created_at
      };

      if (rememberMe) {
        Storage.set('currentUser', userInfo);
      } else {
        SessionStorage.set('currentUser', userInfo);
      }
      return data;
    },

    async signOut() {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');
      const { error } = await client.auth.signOut();
      if (error) throw error;
      Storage.remove('currentUser');
      SessionStorage.remove('currentUser');
    },

    async getCurrentUser() {
      const client = initializeSupabase();
      if (!client) return null;
      const { data: { user }, error } = await client.auth.getUser();
      if (error) { console.error('Error getting user:', error); return null; }
      return user;
    },

    async getSession() {
      const client = initializeSupabase();
      if (!client) return null;
      const { data: { session }, error } = await client.auth.getSession();
      if (error) { console.error('Error getting session:', error); return null; }
      return session;
    },

    async isAuthenticated() {
      return (await this.getSession()) !== null;
    },

    async getUserRole() {
      const user = await this.getCurrentUser();
      return user?.user_metadata?.role || null;
    },

    async logout() { return await this.signOut(); }
  },

  // ── PACKAGES ──────────────────────────────────────────────────────────────
  packages: {

    async getPackages(filters = {}) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');

      let query = client
        .from('packages')
        .select('*')
        .eq('status', 'active')
        .order('created_at', { ascending: false });

      if (filters.category) query = query.eq('category', filters.category);

      const { data, error } = await query;
      if (error) throw error;
      return data || [];
    },

    async getPackage(packageId) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');

      const { data, error } = await client
        .from('packages')
        .select('*')
        .eq('id', packageId)
        .single();
      if (error) throw error;
      return data;
    },

    // Merchant: get own packages
    async getMerchantPackages(merchantId) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');

      const { data, error } = await client
        .from('packages')
        .select('*')
        .eq('merchant_id', merchantId)
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data || [];
    }
  },

  // ── BOOKINGS ──────────────────────────────────────────────────────────────
  bookings: {

    async getBookings(status = null) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');

      let query = client
        .from('bookings')
        .select('*')
        .order('created_at', { ascending: false });

      if (status && status !== 'all') query = query.eq('status', status);

      const { data, error } = await query;
      if (error) throw error;
      return data || [];
    },

    async getBooking(bookingId) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');

      const { data, error } = await client
        .from('bookings')
        .select('*')
        .eq('id', bookingId)
        .single();
      if (error) throw error;
      return data;
    },

    // ✅ FIXED column names: surprise_date, surprise_time, recipient_address
    async createBooking(bookingData) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');

      const { data: { user }, error: userError } = await client.auth.getUser();
      if (userError) throw userError;
      if (!user) throw new Error('User not authenticated');

      console.log('📝 Creating booking:', bookingData);

      const dbBooking = {
        user_id:             user.id,
        package_name:        bookingData.packageName        || bookingData.package_name,
        package_price:       parseFloat(bookingData.packagePrice || bookingData.package_price || bookingData.totalAmount || 0),
        recipient_name:      bookingData.recipientName      || bookingData.recipient_name,
        recipient_phone:     bookingData.recipientPhone     || bookingData.recipient_phone,
        recipient_address:   bookingData.deliveryAddress    || bookingData.recipient_address,
        surprise_date:       bookingData.surpriseDate       || bookingData.surprise_date,
        surprise_time:       bookingData.surpriseTime       || bookingData.surprise_time,
        timezone:            bookingData.timezone           || 'WAT',
        flexible_timing:     bookingData.flexibleTiming     || false,
        personal_message:    bookingData.personalMessage    || bookingData.personal_message    || null,
        special_requests:    bookingData.specialRequests    || bookingData.special_requests    || null,
        addons:              bookingData.addons             || [],
        status:              bookingData.status             || 'pending',
        payment_status:      bookingData.paymentStatus      || bookingData.payment_status      || 'pending',
        payment_reference:   bookingData.paymentReference   || bookingData.payment_reference   || null,
        flutterwave_reference: bookingData.transactionId    || bookingData.flutterwave_reference || null,
        total_amount:        parseFloat(bookingData.totalAmount || bookingData.packagePrice || 0)
      };

      console.log('💾 DB payload:', dbBooking);

      const { data, error } = await client
        .from('bookings')
        .insert(dbBooking)
        .select()
        .single();

      if (error) { console.error('❌ DB insert error:', error); throw error; }
      console.log('✅ Booking created:', data);
      return data;
    },

    async updateBooking(bookingId, updates) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');
      const { data, error } = await client
        .from('bookings').update(updates).eq('id', bookingId).select().single();
      if (error) throw error;
      return data;
    },

    async cancelBooking(bookingId) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');
      const { data, error } = await client
        .from('bookings')
        .update({ status: 'cancelled', cancelled_at: new Date().toISOString() })
        .eq('id', bookingId).select().single();
      if (error) throw error;
      return data;
    },

    async getBookingStats() {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');
      const { data: { user } } = await client.auth.getUser();
      if (!user) throw new Error('User not authenticated');

      const { data, error } = await client
        .from('bookings').select('status, package_price').eq('user_id', user.id);
      if (error) throw error;

      return {
        total:      data.length,
        pending:    data.filter(b => b.status === 'pending').length,
        confirmed:  data.filter(b => b.status === 'confirmed').length,
        processing: data.filter(b => b.status === 'processing').length,
        delivered:  data.filter(b => b.status === 'delivered').length,
        cancelled:  data.filter(b => b.status === 'cancelled').length,
        totalSpent: data
          .filter(b => b.status !== 'cancelled')
          .reduce((sum, b) => sum + parseFloat(b.package_price || 0), 0)
      };
    },

    async searchBookings(searchTerm) {
      const client = initializeSupabase();
      if (!client) throw new Error('Supabase not initialized');
      const { data, error } = await client
        .from('bookings')
        .select('*')
        .or(`booking_reference.ilike.%${searchTerm}%,recipient_name.ilike.%${searchTerm}%,package_name.ilike.%${searchTerm}%,recipient_phone.like.%${searchTerm}%`)
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data || [];
    },

    subscribeToUpdates(callback) {
      const client = initializeSupabase();
      if (!client) { console.error('Supabase not initialized'); return null; }
      const stored = Storage.get('currentUser') || SessionStorage.get('currentUser');
      if (!stored) return null;

      return client
        .channel('bookings-changes')
        .on('postgres_changes',
          { event: '*', schema: 'public', table: 'bookings', filter: `user_id=eq.${stored.id}` },
          payload => { console.log('Booking updated:', payload); if (callback) callback(payload); }
        )
        .subscribe();
    }
  }
};

// ─── Init on DOM ready ────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => { API.init(); });

// ─── Exports ──────────────────────────────────────────────────────────────────
window.API             = API;
window.Storage         = Storage;
window.SessionStorage  = SessionStorage;
window.getSupabaseClient = initializeSupabase;

console.log('✅ supabaseApi.js loaded — Role-Aware Version');
